[package]
name = "solver_service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
contracts = { path = "../contracts" }
env_logger = "0.11.8"
log = "0.4.29"
tokio = {version = "1.49.0", features = ["full"]}
wincode = { version = "0.2.5", features = ["std"] }
