
name: Docker Release

on:
  push:
    branches:
      - main  

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Problem Docker image
        run: |
          docker build -t ghcr.io/torgremm/problem_juggler/problem_service:latest -f problem_service/Dockerfile .

      - name: Build Solver Docker image
        run: |
          docker build -t ghcr.io/torgremm/problem_juggler/solver_service:latest -f solver_service/Dockerfile .

      - name: Build User Docker image
        run: |
          docker build -t ghcr.io/torgremm/problem_juggler/user_service:latest -f user_service/Dockerfile .

      - name: Push Problem Docker image
        run: |
          docker push ghcr.io/torgremm/problem_juggler/problem_service:latest

      - name: Push Solver Docker image
        run: |
          docker push ghcr.io/torgremm/problem_juggler/solver_service:latest

      - name: Push User Docker image
        run: |
          docker push ghcr.io/torgremm/problem_juggler/user_service:latest
