name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build
      - name: Build workspace
        run: cargo build --workspace --features test-utils --verbose

      # Step 1: Run unit tests
      - name: Run unit tests for problem service
        working-directory: problem_service
        run: cargo test --lib --verbose

      - name: Run unit tests for solver service
        working-directory: solver_service
        run: cargo test --verbose

      - name: Run unit tests for user service
        working-directory: user_service
        run: cargo test --verbose

      - name: Run unit tests for pretender
        working-directory: pretender
        run: cargo test --verbose


      # Step 2: Stress test
      - name: Run stress test
        run: cargo run -p pretender
